### PR TITLE
Add TV Show ClearArt to OSD for episodes

### PR DESCRIPTION
**Pull request by IchabodFletchman**

### CODE REVIEW

**Comment by phil65** [comment]
With this change it is not possible anymore to see which exact episode is playing, right?

**Comment by IchabodFletchman** [comment]
You can still see episode details (ie S1E5) and the episode title. It shows to the right of the logo

**Comment by phil65** [comment]
Does that look fine? A screenshot would be nice.

**Comment by IchabodFletchman** [comment]
I think it looks pretty good
osd

**Comment by phil65** [comment]
Does it work with extra-long episode names? Perhaps better a separate control instead of slide animation?

**Pull request merged**
