### PR TITLE
Update Hebrew translation

### PR DESCRIPTION
**Pull request by Eng2Heb**
Add missing strings and fix translation

### CODE REVIEW

**Comment by Eng2Heb** [comment]
The continuous-integration/travis-ci/pr system has an error. Its shows an error but the translation is OK.
Pls merge it.

**Comment by phil65** [comment]
translations belong into transifex, not here.

**Comment by Eng2Heb** [comment]
I'm a member in https://www.transifex.com/ 
The problem is the strings I translated not even chekced. 
It looks like the only 1 Hebrew translations coordinator has left.
What do you suggest to do?

**Comment by phil65** [comment]
The problem might be that I did not sync the translations for a longer time. ;)

**Pull request closed without merging**
