### PR TITLE
Fixes the Wall-View as at the bottom the icons are cutted

### PR DESCRIPTION
**Pull request by DaVukovic**
If "height" is at 100% the icons at the bottom are not completely visible. 

See:

bildschirmfoto vom 2017-01-27 19-06-19

with that change it will look like:

bildschirmfoto vom 2017-01-27 20-00-06

At least it fixes it for me ;)

### CODE REVIEW

**Comment by DaVukovic** [comment]
I guess that's not needed to be merged. I found out, that the problem on the view I had was caused by the 16:10 monitor I use on my PC. I don't have that 'problem' on my main HTPC and my 16:9 TV. So, tbh, not 100% sure if that is really needed.

Sorry for the noise.

**Comment by da-anda** [comment]
I also ran into this display issue twice. I think it was related to the fact that I had resized the window. Was not able to reproduce ever since.

**Comment by DaVukovic** [comment]
Yes, I could only reproduce it with a 16:10 monitor. But I can't reproduce it anymore on that as well. No matter if I resize the window or being in fullscreen. So things have been fixed (somehow ;) ).

**Comment by phil65** [comment]
These kind of issues might appear for specific screen px heights atm, but would have to get fixed in a different way (we would basically need a fixedllist-panel or sth like that.)

**Pull request closed without merging**
