### PR TITLE
Added missing strings

### PR DESCRIPTION
**Pull request by Eng2Heb**
Added missing strings by the English file

### CODE REVIEW

**Comment by Eng2Heb** [comment]
The code is clean. It looks like the Travis CI build has an error

**Comment by phil65** [comment]
yup i know, Travis CI for skins is still WIP.

**Comment by Eng2Heb** [comment]
Hi,
Can you merge my changes?

בכבוד רב,
ערן בודנקין
053-5555120

2017-10-09 17:31 GMT+03:00 Philipp Temminghoff <notifications@github.com>:

**Comment by phil65** [comment]
Translations should be done via Transifex, not pull requests.

**Pull request closed without merging**
