### PR TITLE
PVR menu suggestions

### PR DESCRIPTION
**Pull request by hackthis02**
I've made some changes I wanted to propose to you. 

**Home**:
+Reordered recent recordings and channels (_thought recent recordings would be more used than recent channels_)
+Add episode name and reordered info on WeidgetListRecordings (_displays the episode name in the event you have more then one of the same show_)
**Recordings menu**:
+Replaced title on sidebar with episode name (_thought this looked cleaner than having the title on the screen twice_)
+changed date to StartDate (_adds the day the recording was made which make it easier to determine when the show was aired_)
+changed ActualIcon to Icon on sidebar (_so it displays the show thumbnail_)

Here the examples:
[Home](http://imgur.com/HmzDgWy)
[PVR Recordings](http://imgur.com/KKMNW8V)

### CODE REVIEW

**Comment by phil65** [comment]
I am fine with all except

+Reordered recent recordings and channels (thought recent recordings would be more used than recent channels)

it might be worth havin a look at our home_alt branch (still kind of "secret"). Future PR´s might be better for that branch.

**Comment by hackthis02** [comment]
Thanks. I didn't notice that branch. Would it be better for you if I reverted the channel/recordings reorder on this PR or make a new one against home_alt?

**Comment by phil65** [comment]
adjust this PR please and set up a new one for home_alt in case it is needed. Quite a few things changed.

**Comment by hackthis02** [comment]
Fixed the reorder. I'll look at home_alt next and adding the changes to that branch as well.

**Comment by phil65** [comment]
your revert is incomplete, look at the diff. ;)

**Comment by hackthis02** [comment]
You're right. Fixed.

**Comment by ksooo** [comment]
Please see my comments in your other PR. They all apply to this PR as well.

**Comment by hackthis02** [comment]
This one has been updated.

**Comment by hackthis02** [comment]
This branch should be ready to merge. If I didn't squash correctly let me know, As I've said before I'm new to git.

**Comment by phil65** [comment]
this pr is also borked.

**Comment by hackthis02** [comment]
I don't see anything wrong. What am I missing?

**Comment by phil65** [comment]
Also here, look at the diff, this contains lot of changes which shouldnt be included.

**Comment by hackthis02** [comment]
Hopefully that fixes this branch.

**Comment by hackthis02** [comment]
Okay, I think I've fixed everything. Confirm that before I squash it again.

**Comment by hackthis02** [comment]
This conflict is not, I'll check it out.

**Comment by hackthis02** [comment]
Okay this PR has become a dumper fire. So I'm going to close it, update my repo to current and submit a new on.

**Pull request closed without merging**
