### PR TITLE
PVR menu suggestions

### PR DESCRIPTION
**Pull request by hackthis02**
I'm resubmitting this pull request. Since that last one became such a dumper fire.

Home:
+Add episode name and reordered info on WeidgetListRecordings
Recordings menu:
+Moved episode name to under title on sidebar
+changed ActualIcon to Icon on sidebar

### CODE REVIEW

**Comment by phil65** [comment]
https://github.com/phil65/skin.estuary/commit/c4008c8fffb45dbd65eb867e164bc6abaab1d592 doesnt really doesnt make me too confident that you always have the full picture about the scope of your changes...
Please do separate PRs for each atomical change.

**Comment by hackthis02** [comment]
I guess I don't understand the issue?
I had removed ListItem.EpisodeName from the list because I moved it over to the sidebar.

**Comment by phil65** [comment]
lot of recordings are only distingishuable by episodename. so if you remove episodename from the list, you often end up with lot of entries with same label and user needs to scroll over each one to find the correct one.

**Comment by hackthis02** [comment]
haha I see what your saying. In effect I'm creating the very issue I wanted to fix on the home screen by added the episode name to the WeidgetListRecordings

**Comment by hackthis02** [comment]
I reverted that section of the PR. Thanks for pointing out that issue.

**Pull request closed without merging**
